name: Frontend Tests
on: [push]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@v3
    - name: Install packages
      run: npm ci
    - name: Jest
      run: npx jest